FROM borda/docker_python-opencv-ffmpeg:cpu-py3.10-cv4.8.1

WORKDIR /app

COPY ./requirements-cpu.txt requirements.txt

RUN pip install --upgrade pip setuptools && \
    pip install ultralytics --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir --ignore-installed -r requirements.txt

COPY ./src/ ./src

EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
