services:
  faceapi-cpu:
    image: faceapi.cpu:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    container_name: faceapi_cpu
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
